// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsVKK8Fn0TyOWvFnQWo4R4fjDHpwQG9Bg',
    appId: '1:864914859692:web:5605af0808d4a97b636109',
    messagingSenderId: '864914859692',
    projectId: 'volt-rush',
    authDomain: 'volt-rush.firebaseapp.com',
    storageBucket: 'volt-rush.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfPJ4_3MDyKSbqZGuZpeBXnhaAZcX-O9Q',
    appId: '1:864914859692:android:effef292a6d5984f636109',
    messagingSenderId: '864914859692',
    projectId: 'volt-rush',
    storageBucket: 'volt-rush.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx37CAeglb45WB2Bys3tWjS-tiRSCl3JM',
    appId: '1:864914859692:ios:8b94a108839b06c7636109',
    messagingSenderId: '864914859692',
    projectId: 'volt-rush',
    storageBucket: 'volt-rush.firebasestorage.app',
    iosBundleId: 'com.hexivine.voltrush',
  );
}
